export const environment = {
    production: true,
    token: '',
    fullName: '',
    id: 0,
    picture: '',
    email: '',
    type: '',
    city: '',
    phone: '',
    pictureFormation: '',
    temaFormation: '',
    descriptionFormation: '',
    skill:'',
};
